<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE" />
  <title>Dev</title>

        <link rel="stylesheet" type="text/css" href="/yui/build/reset-fonts-grids/reset-fonts-grids.css"></link>
        <link rel="stylesheet" type="text/css" href="/yui/build/assets/skins/sam/button.css"></link>
        <link rel="stylesheet" type="text/css" href="/yui/build/container/assets/skins/sam/container.css"></link>
        <link rel="stylesheet" type="text/css" href="/yui/build/datatable/assets/skins/sam/datatable.css"></link>        
        <link rel="stylesheet" type="text/css" href="/yui/build/assets/skins/sam/resize.css"></link>
        <link rel="stylesheet" type="text/css" href="/yui/build/tabview/assets/skins/sam/tabview.css"></link>
        <link rel="stylesheet" type="text/css" href="/yui/build/assets/skins/sam/layout.css"></link>
        <link rel="stylesheet" type="text/css" href="/yui/build/calendar/assets/skins/sam/calendar.css"></link>
        <link rel="stylesheet" type="text/css" href="/yui/build/carousel/assets/skins/sam/carousel.css"></link>
        <link rel="stylesheet" type="text/css" href="/css/default.css"></link>
        
        <script type="text/javascript" src="/yui/build/yahoo-dom-event/yahoo-dom-event.js"></script>
        <script type="text/javascript" src="/yui/build/connection/connection-min.js"></script>
        <script type="text/javascript" src="/yui/build/element/element-min.js"></script>
        <script type="text/javascript" src="/yui/build/tabview/tabview-min.js"></script>
        <script type="text/javascript" src="/yui/build/button/button-min.js"></script>
        <script type="text/javascript" src="/yui/build/dragdrop/dragdrop-min.js"></script>
        <script type="text/javascript" src="/yui/build/container/container-min.js"></script>
        <script type="text/javascript" src="/yui/build/resize/resize-min.js"></script>
        <script type="text/javascript" src="/yui/build/animation/animation-min.js"></script>
        <script type="text/javascript" src="/yui/build/layout/layout-min.js"></script>
        <script type="text/javascript" src="/yui/build/datasource/datasource-min.js"></script>
        <script type="text/javascript" src="/yui/build/event-delegate/event-delegate-min.js"></script>
        <script type="text/javascript" src="/yui/build/datatable/datatable-min.js"></script>
        <script type="text/javascript" src="/yui/build/calendar/calendar-min.js"></script>
        <script type="text/javascript" src="/yui/build/carousel/carousel-min.js"></script>
        
</head>
<body class="yui-skin-sam">
    
    <div id="custom-doc">
        <div id="header"><img src="/images/stahls.png" />
        <ul>
<li><a href="/">FORSIDE</a>
</li>
<li><a href="#nogo">PRODUKTER</a>
</li>
<li><a href="#nogo">INFORMATION</a>
</li>
<li><a href="#nogo">SUPPORT</a>
</li>
<li><a href="#nogo">KONTAKT</a>
</li>

</ul>
        </div>
    
        
    <div class="yui-g">
        <div class="yui-u first" id="left">
            <ul class="nav">
            <li>
		<a href="#">Skilte
                    <span>Alle slags skilte. Reflektive, Graveret, Fascade skilte</span>
		</a>
	</li>
	<li>
		<a href="#">Visit Kort
		<span>Din personlige profil - Forskellen mellem success & fiasko </span>
		</a>
	</li>
	<li>
		<a href="#">Stor Format Print
		<span>Blandit turpis patria euismod at iaceo appellatio, demoveo esse. Tation utrum utrum abigo demoveo immitto aliquam sino aliquip. </span>
		</a>
	</li>
        <li>
		<a href="#">Bannere
                    <span>Polyester & PVC Bannere digital trykt i photo kvalitet </span>
		</a>
	</li>
            </ul>
            
            <img src="/images/products/cards.png"/>
        </div>
        
       
<div class="yui-u first" id="center">
    <div class="yui-g flow">
       <img src="/images/products/progress.jpg"/>
        <div class="yui-u first" style="width:30%;">
            1. Select Product
        </div>
        <div class="yui-u first" style="width:30%;">
            2. Upload Design
        </div>
        <div class="yui-u" style="width:30%;">
           3. Complete
        </div>
       
    </div>
    <div class="desc">
        <div class="yui-g">
            <div class="yui-u first">
                <img src="/images/products/flyers.jpg"></img>
            </div>
            <div class="yui-u desc-item">
                <ul><li>Quality : <em class="format"></em></li><li>Color : 1 side full colour</li></ul>
            </div>
        </div>
    </div>
    <div id="tvcontainer" class="yui-navset">
    <ul class="yui-nav">
        <li class="selected"><a href="#tab1"><em>Silk</em></a></li>
        <li><a href="#tab2"><em>Glans</em></a></li>
        <li><a href="#tab3"><em>Mat</em></a></li>
        <li><a href="#tab2"><em>Choose finish </em></a></li>

    </ul>            
    <div class="yui-content">
        <div id="dtcontainer">
            
            
                                <div id="tvcontainer1" class="yui-navset">
                        <ul class="yui-nav">
                            <li class="selected"><a href="#tab1"><em>80gsm</em></a></li>
                            <li><a href="#tab2"><em>135gsm</em></a></li>
                            <li><a href="#tab3"><em>180gsm</em></a></li>

                        </ul>            
                        <div class="yui-content">
                            <div id="dtcontainer11"></div>
                            <div id="dtcontainer12"></div>
                            <div id="dtcontainer13"></div>
                        </div>
                        </div>
    
            
            
            
            
        </div>
        <div id="dtcontainer">
            
            
            
                                    <div id="tvcontainer2" class="yui-navset">
                        <ul class="yui-nav">
                            <li class="selected"><a href="#tab1"><em>80gsm</em></a></li>
                            <li><a href="#tab2"><em>135gsm</em></a></li>
                            <li><a href="#tab3"><em>180gsm</em></a></li>

                        </ul>            
                        <div class="yui-content">
                            <div id="dtcontainer21"></div>
                            <div id="dtcontainer22"></div>
                            <div id="dtcontainer23"></div>
                        </div>
                        </div>

            
            
            
            
        </div>
        <div id="dtcontainer">
            
        
                        <div id="tvcontainer3" class="yui-navset">
                        <ul class="yui-nav">
                            <li class="selected"><a href="#tab1"><em>80gsm</em></a></li>
                            <li><a href="#tab2"><em>135gsm</em></a></li>
                            <li><a href="#tab3"><em>180gsm</em></a></li>

                        </ul>            
                        <div class="yui-content">
                            <div id="dtcontainer31"></div>
                            <div id="dtcontainer32"></div>
                            <div id="dtcontainer33"></div>
                        </div>
                        </div>
            
            
            
        </div>
    </div>
    </div>
    
    
    <!--
     
    -->
        </div>
        
        <div class="yui-u" id="right">
            <div id="basket">
                <span>Basket</span>
                <table>
                    <tr>
                        <th>item</th><th>Qty</th><th>Price</th>
                    </tr>
                    <tr>
                        <td class="one">T-Shirt - Black</td><td class="two">2</td><td class="three">&pound;49.00</td>
                    </tr>
                    <tr>
                        <td class="one">T-Shirt - Black</td><td class="two">2</td><td class="three">&pound;49.00</td>
                    </tr>
                    <tr>
                        <td class="one">T-Shirt - Black</td><td class="two">2</td><td class="three">&pound;49.00</td>
                    </tr>
                    <tr>
                        <td class="one" colspan="2">Total :</td><td class="three">147.00</td>
                    </tr>
                </table>
            </div>
            <div class="newsletter">
                <img src="/images/products/deals.jpg"></img>
            </div>
        </div>
    </div>
    


        
        
<div id="ft">
            <a href="/index/privacy">Privacy Policy</a> | <a href="/index/terms">Terms of Use</a> | <a href="/index/tm">Permissions &#38; trademarks</a><br />

Copyright &#169; 2007-2011 Kindlev Entreprise. All Rights Reserved.
        </div>
    </div>

</body>
<script>
    
(function () {
       var Dom = YAHOO.util.Dom,
        Event = YAHOO.util.Event,
        layout = null;
        
    YAHOO.example.Data = 
        <?php echo $this->data?>
    
    
    
        
    YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.TabView = function() {
        var myColumnDefs = [
            {key:"id", sortable:true,"hidden":true},
            {key:"qty",label:"Antal"},
            {key:"100x210",label:"100 x 210",formatter:YAHOO.widget.DataTable.formatCurrency},
            {key:"105x105",label:"105 x 105",formatter:YAHOO.widget.DataTable.formatCurrency},
            {key:"105x148a6",label:"A6",formatter:YAHOO.widget.DataTable.formatCurrency},
            {key:"148x148",label:"148 x 148",formatter:YAHOO.widget.DataTable.formatCurrency},
            {key:"105x210dl",label:"105 x 210",formatter:YAHOO.widget.DataTable.formatCurrency},
            {key:"105x297",label:"105 x 297",formatter:YAHOO.widget.DataTable.formatCurrency},
            {key:"120x120",label:"120 x 120",formatter:YAHOO.widget.DataTable.formatCurrency}
        ];
        
        
        var setupDataSource = function(format) {
            var data = YAHOO.example.Data.test[format];
            var standardDataSource =  new YAHOO.util.DataSource(data);
            standardDataSource.responseType = YAHOO.util.DataSource.TYPE_JSARRAY;
            standardDataSource.responseSchema = {
                fields: ["id","qty","100x210","105x105","105x148a6","148x148","105x210dl","105x297","120x120"]
            };
            
            return standardDataSource;
        }
        
        var setupTable = function(container, format) {
            //var container = dtcontainer11;
            //var format = gloss;
            
            var dataTable =  new YAHOO.widget.DataTable(container, myColumnDefs, setupDataSource(format),{
                scrollable:true,
                width:"100%",
                currencyOptions:{suffix: ' kr.', decimalPlaces:0, decimalSeparator:',', thousandsSeparator:'.'}
            });
            
            dataTable.subscribe("cellMouseoverEvent", dataTable.onEventHighlightCell);
            dataTable.subscribe("cellMouseoutEvent", dataTable.onEventUnhighlightCell);
            dataTable.subscribe("cellClickEvent", function(e) {
                var target = e.target,
                record = this.getRecord(target),
                column = this.getColumn(target);           
                alert(column.innerHTML);
            });
            
            
            return dataTable;
        };
        
        setupTable("dtcontainer11","standard");
        setupTable("dtcontainer12","gloss");
        setupTable("dtcontainer13","matt");
        setupTable("dtcontainer21","standard");
        setupTable("dtcontainer22","gloss");
        setupTable("dtcontainer23","matt");
        setupTable("dtcontainer31","standard");
        setupTable("dtcontainer32","gloss");
        setupTable("dtcontainer33","matt");
        
        
        var changeText =  function(value, value2) {
            Dom.getElementsByClassName('format')[0].innerHTML = value2;
        }
        /*
        var myDataTable2 = 
                new YAHOO.widget.DataTable("dtcontainer11", myColumnDefs, setupDataSource('matt'),{
                scrollable:true,
                width:"100%",
                currencyOptions:{suffix: ' kr.', decimalPlaces:0, decimalSeparator:',', thousandsSeparator:'.'}
            });
            
        var myDataTable3 = 
                new YAHOO.widget.DataTable("dtcontainer21", myColumnDefs, setupDataSource('standard'),{
                scrollable:true,
                width:"100%",
                currencyOptions:{suffix: ' kr.', decimalPlaces:0, decimalSeparator:',', thousandsSeparator:'.'}
            });
            
        myDataTable2.subscribe("cellMouseoverEvent", myDataTable2.onEventHighlightCell);
        myDataTable2.subscribe("cellMouseoutEvent", myDataTable2.onEventUnhighlightCell);
        */    
          
                
        var myTabView0 = new YAHOO.widget.TabView("tvcontainer");
        //myTabView1.getTab(0).addListener("click", function() {myDataTable.onShow()});
        
        var myTabView1 = new YAHOO.widget.TabView("tvcontainer1",{'orientation':'left'});
        var myTabView2 = new YAHOO.widget.TabView("tvcontainer2",{'orientation':'left'});
        var myTabView3 = new YAHOO.widget.TabView("tvcontainer3",{'orientation':'left'});
        //myTabView1.getTab(0).addListener("click", function() {setupTable});
        myTabView1.getTab(1).addListener("click", function() {changeText('newtext','newtext2')});
        //myTabView1.getTab(2).addListener("click", function() {setupTable("dtcontainer13","standard")});
        //myTabView2.getTab(1).addListener("click", function() {setupTable("dtcontainer22","gloss")});
        //myTabView2.getTab(2).addListener("click", function() {setupTable("dtcontainer23","gloss")});
        //myTabView3.getTab(1).addListener("click", function() {setupTable("dtcontainer32","matt")});
        //myTabView3.getTab(2).addListener("click", function() {setupTable("dtcontainer33","matt")});
        //myTabView0.getTab(3).set('disabled', true);
        
        return {
            oDS: setupDataSource,
            oDT: setupTable,
            oTV: myTabView0
        };
    }();
});    
        
        
        
        
    Event.onDOMReady(function() {
        var carousel = new YAHOO.widget.Carousel("carousel", {
            autoPlayInterval: 5000,
            animation: { speed: 0,effect:YAHOO.util.Easing.easeBoth },
            isCircular: true,
            numVisible: 1,
            navigation: { prev: null, next: null }
        });
        carousel.render(); // get ready for rendering the widget
        carousel.startAutoPlay();   // display the widget
            
    });
    })();    
    
</script>
</html>

